[package]
name = "lean-crm"
version = "0.1"
lean_version = "nightly-2019-01-13"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "04b5f885908757bcb3830e21f37d9f38e0d3bf6d"}
